[package]
name = "egui-geode-rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "rust-src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
egui = "0.29"
egui_glow = "0.29"
parking_lot = "0.12"

[build-dependencies]
bindgen = "0.70"

[workspace]
members = ["example/rust-ffi"]
resolver = "2"