[package]
name = "egui-geode"
version = "0.1.0"
edition = "2021"

[lib]
path = "rust/lib/lib.rs"
crate-type = ["lib", "dylib"]

[dependencies]
anyhow = "1.0"
egui = "0.29"
egui_glow = "0.29"

[workspace]
members = [
    "rust/ffi",
    "example/rust-ffi"
]
resolver = "2"