[package]
name = "egui_geode_rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "rust-src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
cxx = "1.0"
egui = "0.29"
egui_glow = "0.29"

[build-dependencies]
cxx-build = "1.0"