[package]
name = "egui_geode_rust_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
egui_geode_rust = { path = ".." }
anyhow = "1.0"
egui = "0.29"
egui_glow = "0.29"